name: 最近のQiita投稿記事をGistとReadme.mdに反映する

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # JST 6:00

jobs:

  build:
    name: Update Qiita Posts
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 218995479e8a32aafab2b2dcd0c096eb
      QIITA_API_KEY: ${{ secrets.QIITA_API_KEY }}
      MARKDOWN_FILE: ../README.md
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          git clone https://github.com/yututi/qiita-box.git
          cd ./qiita-box
          npm install --only=production
          node src/index.js
          cd ../
          rm -rf qiita-box
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git diff
          git add README.md
          git diff-index --quiet HEAD || git commit -m "Update markdown file."
          git push
